vich_uploader:
    db_driver: orm

    mappings:
        realization_image:
            uri_prefix: /images/realization
            upload_destination: '%kernel.project_dir%/public/images/realization'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
