language: php
sudo: false
php:
  - '7.4.0'

services:
  - mysql

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test

script:
  - php bin/phpunit
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report